server:
  port: 8083
  
spring:
  data:
    mongodb:
      uri: mongodb+srv://stanleyvladimir:bar2005XP@cluster0.q4ibd.mongodb.net/meseroapp
  
  main:
    web-application-type: reactive
     
  application:
    name: micro1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true